apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: logging
data:
  metricbeat.yml: |
    metricbeat.modules:
    - module: prometheus
      period: "60s"
      hosts: ["http://thanos-query.thanos.svc.cluster.local:9090"]
      metrics_path: /api/v1/query
      query:
        query: "container_cpu_usage_seconds_total" # debugging
        #query: "{__name__=~\".+\"}"  # 모든 메트릭을 쿼리
      response_format: "protobuf"  # Ensure correct format for parsing
      timeout: "120s"  # 타임아웃 값을 60초로 설정
      http:
        timeout: "120s"  # Set timeout to 60 seconds
        max_retries: 5  # Retry up to 5 times on failure
        keep_alive: true  # Enable HTTP keep-alive
        compression: true  # Enable HTTP compression
        max_redirects: 3  # Allow up to 3 HTTP redirects
      fields:
        include: ["*"]
    output.elasticsearch:
      hosts: ["http://172.31.18.85:9200"]
      #username: "elastic"
      #password: "changeme"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:8.0.0
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          subPath: metricbeat.yml
      volumes:
      - name: config
        configMap:
          name: metricbeat-config
