apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config-for-remote-write
  namespace: logging
data:
  metricbeat.yml: |
    metricbeat.modules:
    - module: prometheus
      metricsets: ["remote_write"]
      host: "0.0.0.0"
      port: "9201"
      use_types: true
      rate_counters: true
      period: 60s
    output.elasticsearch:
      hosts: ["http://172.31.18.85:9200"]
      #username: "elastic"
      #password: "changeme"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  namespace: logging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:8.0.0
        ports:
        - containerPort: 9201
          name: metricbeat
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          subPath: metricbeat.yml
      volumes:
      - name: config
        configMap:
          name: metricbeat-config-for-remote-write

---
apiVersion: v1
kind: Service
metadata:
  name: metricbeat
  namespace: logging
spec:
  ports:
  - port: 9201
    protocol: TCP
    targetPort: 9201
  selector:
    app: metricbeat
  type: ClusterIP
