apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    NHcluster: clusterA
  name: nh-sms-recording.rules
  namespace: cattle-monitoring-system
spec:
  groups:
  - name: cpu_usage_rules
    rules:
    - record: nh_pod_cpu_usage:rate5m
      expr: |
        sum by (container, pod, namespace) (rate(container_cpu_usage_seconds_total{pod!=""}[5m])) 
        / 
        sum by (container, pod, namespace) (kube_pod_container_resource_requests{pod!="" ,resource="cpu"}) 
        * 100
  - name: memory_usage_rules
    rules:
    - record: nh_pod_memory_usage:ratio
      expr: |
        sum by (container, pod, namespace) (container_memory_usage_bytes{pod!=""}) 
        / 
        sum by (container, pod, namespace) (kube_pod_container_resource_requests{pod!="",resource="memory"}) 
        * 100
  - name: pvc_usage
    rules:
    - record: nh_pvc_usage:ratio
      expr: |
        sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes) 
        / 
        sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_capacity_bytes) 
        * 100
