apiVersion: networking.istio.io/v1beta1  
kind: VirtualService  
metadata:  
  name: productpage-tls
  namespace: istio-example  
spec:  
  hosts:  
  - prod.test.dom  
  gateways:  
  - productpage-gateway-tls
  http:  
  - route:  
    - destination:  
        host: productpage.istio-example.svc.cluster.local  
        subset: v1  
      weight: 78  
    - destination:  
        host: productpage.istio-example.svc.cluster.local  
        subset: v2  
      weight: 22
