filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
            and:
              - equals:
                  kubernetes.node.name: rancher-master-test2
              - not:
                  contains:
                    kubernetes.labels.NHapp: "app"
          config:
            - type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
processors:
  - add_kubernetes_metadata:
      in_cluster: false
      host: "https://172.31.39.208:6443"
      ssl.certificate: "/var/lib/rancher/rke2/agent/client-kubelet.crt"
      ssl.key: "/var/lib/rancher/rke2/agent/client-kubelet.key"
      ssl.certificate_authorities:
        - "/var/lib/rancher/rke2/agent/client-ca.crt"
  - add_fields:
      target: ""  
      fields:
        NHcenter: "centerA"
        NHcluster: "clusterA"

output.elasticsearch:
  hosts: ["http://172.31.29.94:9200"]
  index: "k8s-pod-log-system"

setup.template.name: "k8s-pod-log-system"
setup.template.pattern: "k8s-pod-log-system"
