apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: example-alertcfg
  namespace: cattle-monitoring-system
  labels:
    alertconfig: example
spec:
  receivers:
  - name: default-receiver
  route:
#    groupBy: 
#      - NHcluster
#      - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    receiver: default-receiver
   # continue: true
    continue: false
 #   routes:
 #   - matchers:
 #     - name: severity
 #       value: warning
 #       matchType: '='
 #     - name: namespace
 #       value: example
 #       matchType: '='
 #     - name: NHcluster
 #       matchType: '='
 #       value: clusterA
 #     - name: podname
 #       matchType: '=~'
 #       value: ".*example.*"
 #     receiver: default-receiver
