apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: example-alertcfg-nginx
  namespace: example
  #namespace: cattle-monitoring-system
  labels:
    alertconfig: example
spec:
  receivers:
  - name: blackhole
  - name: email-notification-multiple
    emailConfigs:
    - to: 'leeyj7141@naver.com,gptforkernel@gmail.com,leeyj7141@daum.net'
      from: 'leeyj7141@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'leeyj7141@gmail.com'
      authPassword:
        name: alertmanager-email-secret
        key: smtp-password
      requireTLS: true
  - name: email-notification
    emailConfigs:
    - to: 'leeyj7141@naver.com'
      sendResolved: true
      smarthost: 'smtp.gmail.com:587'
      from: 'leeyj7141@gmail.com'
      authUsername: 'leeyj7141@gmail.com'
      authPassword:
        name: alertmanager-email-secret
        key: smtp-password
      requireTLS: true

  route:
    groupBy: 
    #  - NHcluster
    #  - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    receiver: blackhole
    #continue: true
    routes:
    - matchers:
      - name: team
        value: teamA
        matchType: '='
      - name: severity
        value: warning
        matchType: '='
      - name: namespace
        value: example
        matchType: '='
      - name: NHcluster
        matchType: '='
        value: clusterA
      - name: pod
        matchType: '=~'
        value: ".*example.*"
      receiver: email-notification
    - matchers:
      - name: namespace
        value: example
        matchType: '='
      - name: team
        value: teamB
        matchType: '='
      - name: severity
        value: critical
        matchType: '='
      - name: NHcluster
        matchType: '='
        value: clusterA
      - name: pod
        matchType: '=~'
        value: ".*example.*"
      receiver: email-notification-multiple
