global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages

route:
  receiver: cattle-monitoring-system/example-alertcfg/default-receiver
  group_by: ['namespace', 'team', 'NHcluster']
  #group_by: ['alertname', 'namespace', 'team', 'NHcluster']
  continue: false
  routes:
  - receiver: cattle-monitoring-system/example-alertcfg-nginx/blackhole
    matchers:
    - namespace="cattle-monitoring-system"
    continue: true
    routes:
    - receiver: cattle-monitoring-system/example-alertcfg-nginx/email-notification
      matchers:
      - NHcluster="clusterA"
  #    - namespace="example2"
  #    - pod=~".*example.*"
  #    - severity="warning"
      - team="teamA"
      continue: false
    - receiver: cattle-monitoring-system/example-alertcfg-nginx/email-notification-multiple
      matchers:
      - NHcluster="clusterA"
  #    - namespace="example2"
  #    - pod=~".*example.*"
  #    - severity="critical"
      - team="teamB"
      continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
  - receiver: cattle-monitoring-system/example-alertcfg2/webhook
    group_by:
    - job
    matchers:
    - namespace="cattle-monitoring-system"
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
receivers:
- name: cattle-monitoring-system/example-alertcfg/default-receiver
- name: cattle-monitoring-system/example-alertcfg-nginx/blackhole
- name: cattle-monitoring-system/example-alertcfg-nginx/email-notification-multiple
  email_configs:
  - send_resolved: false
    to: leeyj7141@naver.com,gptforkernel@gmail.com,leeyj7141@daum.net
    from: leeyj7141@gmail.com
    hello: localhost
    smarthost: smtp.gmail.com:587
    auth_username: leeyj7141@gmail.com
    auth_password: <secret>
    headers:
      From: leeyj7141@gmail.com
      Subject: '{{ template "email.default.subject" . }}'
      To: leeyj7141@naver.com,gptforkernel@gmail.com,leeyj7141@daum.net
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: cattle-monitoring-system/example-alertcfg-nginx/email-notification
  email_configs:
  - send_resolved: true
    to: leeyj7141@naver.com
    from: leeyj7141@gmail.com
    hello: localhost
    smarthost: smtp.gmail.com:587
    auth_username: leeyj7141@gmail.com
    auth_password: <secret>
    headers:
      From: leeyj7141@gmail.com
      Subject: '{{ template "email.default.subject" . }}'
      To: leeyj7141@naver.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
- name: cattle-monitoring-system/example-alertcfg2/webhook
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    url: <secret>
    url_file: ""
    max_alerts: 0
templates: []
