---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-2
  namespace: tools
  labels:
    NHcluster: clusterA 
    app: appA 
    office: officeA
    team: teamA
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-with-pvc-2
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: circleci/python:3.10.1-buster-node-browsers
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: pvc-nfs-2

