- name: filebeat installation play
  gather_facts: yes
  become: true
  hosts: 
    - master
    - worker
  roles:
    - role: install-filebeat
      vars:
        kubeconfig_path: "/root/.kube/kube_config_cluster.yaml"
