--- 

- name: etc directory backup
  gather_facts: yes
  become: true
  hosts: 
    - master
    - worker
    - logstash
  roles:
    - role: backup-etc

- name: Setup rke2 server configuration
  gather_facts: no
  become: true
  serial: 1
  hosts:
    - master
  roles:
    - role: setup-rke2-server-for-master

- name: Setup rke2-agent configuration
  gather_facts: no
  become: true
  hosts:
    - worker
  roles:
    - role: setup-rke2-agent-for-worker

- name: Setup Monitoring system for elasticsearch
  gather_facts: yes
  become: true
  hosts: 
    - master
    - worker
  roles:
    - role: install-filebeat
      vars:
        kubeconfig_path: "/root/.kube/kube_config_cluster.yaml"
        local_kubeconfig_path: "kubeconfig"
        #local_kubeconfig_path: "/home/rocky/.kube/config"
    - role: install-metricbeat

- name: logstash installation 
  gather_facts: no
  become: true
  hosts: 
    - logstash
  roles:
    - role: install-logstash
