- name: Setup kube-apiserver audit log configuration
  gather_facts: no
  become: true
  serial: 1
  hosts:
    - master
  roles:
    - role: setup-kube-apiserver-audit-log

- name: Setup Monitoring system for elasticsearch
  gather_facts: yes
  become: true
  hosts: 
    - master
    - worker
  roles:
    - role: install-filebeat
      vars:
        kubeconfig_path: "/root/.kube/kube_config_cluster.yaml"
        local_kubeconfig_path: "kubeconfig"
        #local_kubeconfig_path: "/home/rocky/.kube/config"
    - role: install-metricbeat
