apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nfs-server
    meta.helm.sh/release-namespace: ghlee01
  generation: 1
  labels:
    app.kubernetes.io/instance: nfs-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nfs-server-provisioner
    app.kubernetes.io/version: 3.0.0
    helm.sh/chart: nfs-server-provisioner-1.3.0
  name: nfs-server-nfs-server-provisioner
  namespace: ghlee01
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nfs-server
      app.kubernetes.io/name: nfs-server-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nfs-server
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: nfs-server-provisioner
        app.kubernetes.io/version: 3.0.0
        helm.sh/chart: nfs-server-provisioner-1.3.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - rancher-worker-test2
      containers:
      - args:
        - -provisioner=cluster.local/nfs-server-nfs-server-provisioner
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_NAME
          value: nfs-server-nfs-server-provisioner
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/k8s-staging-sig-storage/nfs-provisioner:v3.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
            - /export
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: nfs-server-provisioner
        ports:
        - containerPort: 2049
          name: nfs
          protocol: TCP
        - containerPort: 2049
          name: nfs-udp
          protocol: UDP
        - containerPort: 32803
          name: nlockmgr
          protocol: TCP
        - containerPort: 32803
          name: nlockmgr-udp
          protocol: UDP
        - containerPort: 20048
          name: mountd
          protocol: TCP
        - containerPort: 20048
          name: mountd-udp
          protocol: UDP
        - containerPort: 875
          name: rquotad
          protocol: TCP
        - containerPort: 875
          name: rquotad-udp
          protocol: UDP
        - containerPort: 111
          name: rpcbind
          protocol: TCP
        - containerPort: 111
          name: rpcbind-udp
          protocol: UDP
        - containerPort: 662
          name: statd
          protocol: TCP
        - containerPort: 662
          name: statd-udp
          protocol: UDP
        readinessProbe:
          exec:
            command:
            - ls
            - /export
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - DAC_READ_SEARCH
            - SYS_RESOURCE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /export
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-server-nfs-server-provisioner
      serviceAccountName: nfs-server-nfs-server-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
