apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: tools
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
