apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

resources:
#  - busybox-with-nfs-pvc.yml
  - busybox.yml
  - curl.yml
  - dnsutils.yml
  - nmap.yml

images:
  - name: busybox
    newName: nexus.nhdemo.com:5000/tools/busybox
    newTag: latest
  - name: curlimages/curl
    newName: nexus.nhdemo.com:5000/tools/curl
    newTag: latest
  - name: registry.k8s.io/e2e-test-images/jessie-dnsutils
    newName: nexus.nhdemo.com:5000/tools/jessie-dnsutils
    newTag: 1.3
  - name: securecodebox/nmap
    newName: nexus.nhdemo.com:5000/tools/nmap
    newTag: latest
