apiVersion: v1
kind: Pod
metadata:
  name: nmap
  namespace: tools
spec:
  containers:
  - name: nmap
    image: securecodebox/nmap
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

