apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-sms-log
  namespace: logging
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
