---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      serviceAccountName: logstash-sa
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - logstash
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.9.0
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps aux |grep -i logstash-core | grep -iv grep "
          initialDelaySeconds: 300
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: QUERY_INTERVAL
          value: "1m"
        - name: CPU_QUERY
          value: "http://thanos-query.thanos.svc.cluster.local:9090/api/v1/query?query=nh_pod_cpu_usage:rate5m"
        - name: MEMORY_QUERY
          value: "http://thanos-query.thanos.svc.cluster.local:9090/api/v1/query?query=nh_pod_memory_usage:ratio"
        - name: PVC_QUERY
          value: "http://thanos-query.thanos.svc.cluster.local.:9090/api/v1/query?query=nh_pvc_usage:ratio"
        - name: POD_STATE_QUERY
          value: "http://thanos-query.thanos.svc.cluster.local:9090/api/v1/query?query=kube_pod_status_phase%7Bphase%3D%22Failed%22%7D"
        - name: ES_URL
          value: "http://172.31.18.85:9200"
        - name: ALERT_INDEX
          value: "k8s-metric-alert-%{+YYYY.MM.dd}"
        - name: CPU_CRITICAL_LIMIT
          value: "90"
        - name: CPU_WARNING_LIMIT
          value: "80"
        - name: MEMORY_CRITICAL_LIMIT
          value: "85"
        - name: MEMORY_WARNING_LIMIT
          value: "75"
        - name: PVC_CRITICAL_LIMIT
          value: "85"
        - name: PVC_WARNING_LIMIT
          value: "75"
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline/
        - name: logstash-pipelines
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        - name: sms-log
          mountPath: /var/log/
      - name: busybox
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        image: busybox
        command: ["sleep", "infinity"]
        volumeMounts:
          - name: sms-log
            mountPath: /var/log/
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config-for-sms-agent
      - name: logstash-pipelines
        configMap:
          name: logstash-config-for-sms-agent
      - name: sms-log
        persistentVolumeClaim:
          claimName: logstash-sms-log


