{
 "title": "Node Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[5m])) / sum by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) ((1 - (node_memory_MemAvailable_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"})) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8 or irate(node_network_receive_bytes{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8",
     "legendFormat": "{{instance}}, {{device}}_in"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8 or irate(node_network_transmit_bytes_total{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8 )* -1",
     "legendFormat": "{{instance}}, {{device}}_out"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, (\r\n  sum(node_filesystem_size_bytes{device!=\"shm\", device!=\"tmpfs\", mountpoint!~\".*boot.*\"}) by (instance, mountpoint) -\r\n  sum(node_filesystem_free_bytes{device!=\"shm\", device!=\"tmpfs\", mountpoint!~\".*boot.*\"}) by (instance, mountpoint)\r\n) / \r\n  sum(node_filesystem_size_bytes{device!=\"shm\", device!=\"tmpfs\", mountpoint!~\".*boot.*\"}) by (instance, mountpoint) * 100\r\n)\r\n",
     "legendFormat": "{{instance}}, {{mountpoint}}"
    }
   ]
  }
 ]
}