{
 "title": "Node Exporter All Nodes Overview",
 "description": "Create by yjlee@linux.com",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{job=~\"$job\"}))"
    }
   },
   { "name": "center", "label": "Center", "query": { "query": "label_values(NHcenter)" } }
  ]
 },
 "panels": [
  {
   "title": "All Node Overview [Job: $job, Total: $total]",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_uname_info{NHcenter=\"$center\", job=~\"$job\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{NHcenter=~\"$center\",job=~\"$job\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{NHcenter=~\"$center\",job=~\"$job\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{NHcenter=~\"$center\",job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{NHcenter=~\"$center\",job=~\"$job\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{NHcenter=~\"$center\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(node_memory_Buffers_bytes{NHcenter=~\"$center\",job=~\"$job\"}+\nnode_memory_Cached_bytes{NHcenter=~\"$center\",job=~\"$job\"}) / node_memory_MemTotal_bytes{NHcenter=~\"$center\",job=~\"$job\"} * 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{NHcenter=~\"$center\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{NHcenter=~\"$center\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{NHcenter=~\"$center\",job=~\"$job\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{NHcenter=~\"$center\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{NHcenter=~\"$center\",job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[5m])) / sum by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8 or irate(node_network_receive_bytes{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8",
     "legendFormat": "{{instance}}, {{device}}_in"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8 or irate(node_network_transmit_bytes_total{device!~\"cali.*\", device!~\"vxlan.*\", device!~\"lo.*\"}[5m])*8 )* -1",
     "legendFormat": "{{instance}}, {{device}}_out"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) ((1 - (node_memory_MemAvailable_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"})) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}