{
 "title": "k8s status-3",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "KUBE-API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"}) / count(up{job=\"apiserver\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCd",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-etcd\"}) / count(up{job=\"kube-etcd\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KUBE-CONTROLLER-MANAGER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"}) / count(up{job=\"kube-controller-manager\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KUBE-SCHEDULER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-scheduler\"}) / count(up{job=\"kube-scheduler\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KUBE-PROXY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-proxy\"}) / count(up{job=\"kube-proxy\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "COREDNS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"coredns\"}) / count(up{job=\"coredns\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "COREDNS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"coredns\"}) / count(up{job=\"coredns\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KUBE-STATE-METRIC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-state-metrics\"}) / count(up{job=\"kube-state-metrics\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "THANOS-QUERY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"thanos-query\"}) / count(up{job=\"thanos-query\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "THANOS-STOREGATEWAY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"thanos-storegateway\"}) / count(up{job=\"thanos-storegateway\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "THANOS-COMPACTOR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"thanos-compactor\"}) / count(up{job=\"thanos-compactor\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPOMETHEUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"rancher-monitoring-prometheus\"}) / count(up{job=\"rancher-monitoring-prometheus\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ALERTMANAGER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"rancher-monitoring-alertmanager\"}) / count(up{job=\"rancher-monitoring-alertmanager\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRAFANA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"rancher-monitoring-grafana\"}) / count(up{job=\"rancher-monitoring-grafana\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KUBELET",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"kubelet\"}) / count(up{job=\"kubelet\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NODE-EXPORTER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"node-exporter\"}) / count(up{job=\"node-exporter\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kube-apiserver\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kube-scheduler\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kube-controller-manager\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"etcd\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"query\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"storegatewa\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"rke2-ingress-nginx-controller\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"etcd\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"kube-apiserver\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"kube-scheduler\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"kube-controller-manager\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"query\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"storegateway\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"grafana\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"coredns\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"alertmanager\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"prometheus\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"kube-state-metrics\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INGRESS-CONTROLLER",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"ingress-nginx\"}) / count(up{job=\"ingress-nginx\"})) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Latency by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])) by (le, host))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}