---
# tasks file for setup-rke2-agent-for-worker

- name: Copy rancher rke2 config.yaml 
  copy:
    src: "kubelet-config.yaml"
    dest: "/etc/rancher/rke2/config.yaml.d/"
    mode: '0644'
  register: rke2_config_output
  notify:
    - Restart rke2-agent

- name: Force handlers to run
  meta: flush_handlers

- name: Wait for rke2-agent service to be active
  command: >
    bash -c 'systemctl is-active rke2-agent'
  register: wait_result
  until: wait_result.rc == 0
  retries: 36
  delay: 5
  changed_when: false
