apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cpu-alerts3
  namespace: thanos
data:
  nginx-cpu3.yml: |
    groups:
    - name: nginx-cpu-alerts3
      rules:
      - alert: ExampleAlertNginxHighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="example", pod=~"nginx-example3.*"}[5m])) by (pod) / sum(kube_pod_container_resource_requests{namespace="example", pod=~"nginx-example3.*", resource="cpu"}) by (pod) > 0.6
        for: 30s
        labels:
          severity: warning
          podname: "{{ $labels.pod }}"
          namespace: "{{ $labels.namespace }}"
        annotations:
          summary: "High CPU usage detected on Nginx Pod ({{ $labels.pod }})"
          description: "CPU usage on Nginx pod {{ $labels.pod }} has exceeded 60% for more than 5 minutes."

    - name: nginx-memory-alerts
      rules:
      - alert: ExampleAlertNginxHighMemoryUsage
        expr: sum(container_memory_usage_bytes{namespace="cattle-monitoring-system", pod=~"prometheus-rancher-monitoring-prometheus.*"}) by (pod) / sum(kube_pod_container_resource_requests{namespace="cattle-monitoring-system", pod=~"prometheus-rancher-monitoring-prometheus.*", resource="memory"}) by (pod) > 0.5
        #expr: sum(container_memory_usage_bytes{namespace="example", pod=~"nginx-example3.*"}) by (pod) / sum(kube_pod_container_resource_requests{namespace="example", pod=~"nginx-example3.*", resource="memory"}) by (pod) > 0.5
        for: 30s 
        labels:
          severity: warning
          namespace: "{{ $labels.namespace }}"
        annotations:
          summary: "High Memory usage detected on Nginx Pod ({{ $labels.pod }})"
          description: "Memory usage on Nginx pod {{ $labels.pod }} has exceeded 50% for more than 5 minutes."
    
