type: s3
config:
  bucket: thanos
  endpoint: 172.31.39.208:30927
  access_key: minio
  secret_key: minio123
  insecure: false
  signature_version2: false
  http_config:
    insecure_skip_verify: true
    tls_config:
      insecure_skip_verify: true
  trace: 
    enable: false
