prometheus:
  prometheusSpec:
    externalLabels:
      cluster: ""
      NHcluster: "clusterA"
    replicas: 2
#    remoteWrite: 
#     - url: http://metricbeat.logging.svc.cluster.local.:9201/write
    thanos:
      objectStorageConfig:
        #key: minio_conf.yml
        key: objstore.yml
        name: thanos-obstore-secret
#  thanosService:
#    annotations: {}
#    clusterIP: ""
#    enabled: true
#    labels: {}
#    port: 10901
#    portName: grpc
#    targetPort: grpc
#    type: ClusterIP
  thanosService:
    enabled: true 
    annotations: {}
    labels: {}
    externalTrafficPolicy: Cluster
    type: ClusterIP
    portName: grpc
    port: 10901
    targetPort: "grpc"
    httpPortName: http
    httpPort: 10902
    targetHttpPort: "http"
    clusterIP: ""
    nodePort: 30901
    httpNodePort: 30902

alertmanager:
  enabled: true
  alertmanagerSpec:
    logLevel: debug
    alertmanagerConfiguration: 
      name: example-alertcfg
    clusterGossipInterval: "15s"
    replicas: 1
    #replicas: 3
    alertmanagerConfigSelector:
      matchExpressions:
        - key: alertconfig
          operator: In
          values:
            - example
            - example-config
  service:
    type: NodePort
    nodePort: 31112

grafana: 
  replicas: 1
  image: 
    repository: rancher/mirrored-grafana-grafana
    tag: 10.3.3
  service:
    type: NodePort
    nodePort: 31111
    isessionAffinity: ClientIP

kube-state-metrics:
  replicas: 2

prometheus-adapter:
  replicas: 2
