apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elk-beats

resources:
- ../../base/

images:
  - name: docker.elastic.co/logstash/logstash
    newTag: 8.9.0

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: logstash
    spec:
      replicas: 2
      template:
        spec:
          containers:
            - name: logstash
              env:
                - name: QUERY_INTERVAL
                  value: "30s"
                - name: CPU_QUERY
                  value: "http://thanos-query.thanos.svc.cluster.local:9090/api/v1/query?query=nh_pod_cpu_usage:rate5m"
                - name: MEMORY_QUERY
                  value: "http://thanos-query.thanos.svc.cluster.local:9090/api/v1/query?query=nh_pod_memory_usage:ratio"
                - name: PVC_QUERY
                  value: "http://thanos-query.thanos.svc.cluster.local.:9090/api/v1/query?query=nh_pvc_usage:ratio"
                - name: POD_STATE_QUERY
                  value: "http://thanos-query.thanos.svc.cluster.local:9090/api/v1/query?query=kube_pod_status_phase%7Bphase%3D%22Failed%22%7D"
                - name: ES_URL
                  value: "http://172.31.18.85:9200"
                - name: ALERT_INDEX
                  value: "k8s-metric-alert-%{+YYYY.MM.dd}"
                - name: CPU_CRITICAL_LIMIT
                  value: "30"
                - name: CPU_WARNING_LIMIT
                  value: "20"
                - name: MEMORY_CRITICAL_LIMIT
                  value: "25"
                - name: MEMORY_WARNING_LIMIT
                  value: "15"
                - name: PVC_CRITICAL_LIMIT
                  value: "55"
                - name: PVC_WARNING_LIMIT
                  value: "45"
  target:
    kind: Deployment
    name: logstash
- patch: |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: logstash-sms-log
    spec:
      resources:
        requests:
          storage: 1Gi
  target:
    kind: PersistentVolumeClaim
    name: logstash-sms-log
- path: logstash-configmap-for-alert-ceneterA-clusterA.yaml
