---
# vars file for install-logstash

logstash_package: "logstash-1:8.9.0-1.x86_64"
thanos_url: "http://3.38.76.78:30008"
query_interval: "30s"
cpu_query: "{{ thanos_url }}/api/v1/query?query=nh_pod_cpu_usage:rate5m"
memory_query: "{{ thanos_url }}/api/v1/query?query=nh_pod_memory_usage:ratio"
pvc_query: "{{ thanos_url }}/api/v1/query?query=nh_pvc_usage:ratio"
pod_state_query: "{{ thanos_url }}/api/v1/query?query=kube_pod_status_phase%7Bphase%3D%22Failed%22%7D"
es_url: "http://172.31.18.85:9200"
alert_index: "k8s-metric-alert-%{+YYYY.MM.dd}"
cpu_critical_limit: "30"
cpu_warning_limit: "20"
memory_critical_limit: "25"
memory_warning_limit: "15"
pvc_critical_limit: "55"
pvc_warning_limit: "45"
sms_agent_log_path: "/var/log/logstash/prometheus_metrics_to_sms_agent.log"
