kubectl delete -n cattle-fleet-local-system   app.catalog.cattle.io/fleet-agent-local
kubectl delete -n cattle-fleet-system   app.catalog.cattle.io/fleet-crd
kubectl delete -n cattle-provisioning-capi-system   app.catalog.cattle.io/rancher-provisioning-capi
kubectl delete -n cert-manager   app.catalog.cattle.io/cert-manager
kubectl delete -n kube-system   app.catalog.cattle.io/my-release
kubectl delete -n cattle-fleet-system   operation.catalog.cattle.io/helm-operation-r8lk4
kubectl delete -n cattle-provisioning-capi-system   operation.catalog.cattle.io/helm-operation-48jbb
kubectl delete -n cluster-fleet-local-local-1a3d67d0a899   bundledeployment.fleet.cattle.io/fleet-agent-local
kubectl delete -n fleet-local   bundle.fleet.cattle.io/fleet-agent-local
kubectl delete -n fleet-local   clustergroup.fleet.cattle.io/default
kubectl delete -n fleet-local   clusterregistration.fleet.cattle.io/request-hq9vw
kubectl delete -n fleet-local   clusterregistrationtoken.fleet.cattle.io/import-token-local
kubectl delete -n fleet-local   cluster.fleet.cattle.io/local
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-alcide-advisor-cronjob
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-aws-event-sources
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-cloudcasa
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-dynatrace-oneagent-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-dynatrace-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-hpe-csi-driver
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-kong
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-mariadb
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-nginx-ingress
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-openebs
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/helm3-library-rancher-externalip-webhook
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-appdynamics-cluster-agent
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-argo-cd
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-artifactory-ha
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-artifactory-jcr
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-aws-event-sources
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-bluehub
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-cert-manager
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-chartmuseum
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-citrix-adc-istio-ingress-gateway
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-citrix-api-gateway
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-citrix-cpx-istio-sidecar-injector
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-citrix-k8s-cpx-ingress-controller
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-citrix-k8s-ingress-controller
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-cockroachdb
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-cost-analyzer
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-datadog
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-docker-registry
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-drone
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-efk
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-etcd-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-fluentd-aggregator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-flux
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-folding-at-home
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-grafana
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-hadoop
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-haproxy
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-harbor
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-harbor-scanner-trivy
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-harness-delegate
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-hpe-flexvolume-driver
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-instana-agent
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-istio
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-kafka
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-kubeflow
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-kubemq
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-kubernetes-dashboard
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-lightstep
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-longhorn
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-magento
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-mariadb
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-memcached
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-mongodb
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-mongodb-replicaset
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-mysql
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-neuvector
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-nfs-provisioner
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-openebs
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-openfaas
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-phpbb
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-portshift-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-portworx
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-portworx-essentials
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-prometheus
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-redis
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-redskyops
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-splice-helm
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-storageos-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-sysdig
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-tidb-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-traefik
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-vault-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-windocks
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/library-wordpress
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/system-library-rancher-cis-benchmark
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/system-library-rancher-external-dns
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/system-library-rancher-gatekeeper-operator
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/system-library-rancher-istio
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/system-library-rancher-k3s-upgrader
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/system-library-rancher-logging
kubectl delete -n cattle-global-data   catalogtemplate.management.cattle.io/system-library-rancher-monitoring
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-alcide-advisor-cronjob-2.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-aws-event-sources-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-aws-event-sources-0.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-aws-event-sources-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-aws-event-sources-0.1.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-cloudcasa-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-dynatrace-oneagent-operator-0.10.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-dynatrace-oneagent-operator-0.7.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-dynatrace-oneagent-operator-0.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-dynatrace-oneagent-operator-0.8.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-dynatrace-oneagent-operator-0.9.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-dynatrace-operator-0.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-hpe-csi-driver-1.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-hpe-csi-driver-1.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-hpe-csi-driver-1.4.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-kong-1.5.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-kong-1.9.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-mariadb-7.3.14
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-nginx-ingress-0.7.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-nginx-ingress-0.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-nginx-ingress-0.9.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-openebs-2.5.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-rancher-externalip-webhook-0.1.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/helm3-library-rancher-externalip-webhook-0.1.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-appdynamics-cluster-agent-20.7.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-argo-cd-2.3.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-0.12.16
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-0.2.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-0.4.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-0.7.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-0.7.12
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-0.7.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-0.8.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-2.2.9
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-ha-2.5.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-jcr-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-jcr-2.1.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-artifactory-jcr-2.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-aws-event-sources-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-bluehub-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-cert-manager-v0.3.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-cert-manager-v0.4.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-cert-manager-v0.5.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-chartmuseum-1.6.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-chartmuseum-1.6.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-chartmuseum-2.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-adc-istio-ingress-gateway-1.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-adc-istio-ingress-gateway-1.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-api-gateway-1.8.19
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-cpx-istio-sidecar-injector-1.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-cpx-istio-sidecar-injector-1.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-cpx-istio-sidecar-injector-1.2.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-cpx-istio-sidecar-injector-1.2.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-k8s-cpx-ingress-controller-1.6.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-k8s-cpx-ingress-controller-1.7.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-k8s-cpx-ingress-controller-1.8.19
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-k8s-cpx-ingress-controller-1.8.28
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-k8s-ingress-controller-1.6.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-k8s-ingress-controller-1.7.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-citrix-k8s-ingress-controller-1.8.19
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-cockroachdb-2.1.16
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-cost-analyzer-1.57.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-datadog-1.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-datadog-1.21.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-datadog-1.33.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-datadog-2.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-docker-registry-1.4.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-docker-registry-1.6.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-docker-registry-1.8.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-docker-registry-1.9.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-drone-1.4.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-drone-1.7.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-drone-2.0.7
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-efk-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-efk-0.1.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-efk-7.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-etcd-operator-0.7.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-etcd-operator-0.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-etcd-operator-0.9.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-fluentd-aggregator-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-fluentd-aggregator-0.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-fluentd-aggregator-0.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-fluentd-aggregator-0.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-flux-1.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-folding-at-home-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-folding-at-home-0.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-grafana-0.0.31
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-grafana-3.8.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-hadoop-1.0.7
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-hadoop-1.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-haproxy-1.1.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-haproxy-1.4.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-harbor-1.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-harbor-1.3.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-harbor-scanner-trivy-0.6.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-harness-delegate-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-hpe-flexvolume-driver-3.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-hpe-flexvolume-driver-3.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-hpe-flexvolume-driver-3.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.16
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.17
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.18
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.19
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.20
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.21
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.22
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.24
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.25
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.26
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.27
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.28
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.29
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.30
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.31
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.32
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-instana-agent-1.0.33
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-istio-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-istio-1.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-istio-1.0.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kafka-0.7.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kafka-0.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kubeflow-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kubeflow-0.6.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kubemq-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kubernetes-dashboard-0.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kubernetes-dashboard-1.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-kubernetes-dashboard-1.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-lightstep-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.3.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.3.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.4.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.4.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.5.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.6.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.6.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.6.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.7.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-0.8.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.1.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.2.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.2.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.2.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-longhorn-1.2.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-magento-1.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-magento-5.1.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mariadb-3.0.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mariadb-4.4.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mariadb-5.0.9
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mariadb-6.7.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mariadb-7.3.14
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-memcached-2.0.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-memcached-2.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-memcached-2.9.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mongodb-2.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mongodb-5.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mongodb-7.2.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mongodb-replicaset-3.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mongodb-replicaset-3.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mongodb-replicaset-3.9.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mysql-0.3.7
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mysql-0.3.8
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-mysql-1.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-neuvector-1.2.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-neuvector-1.5.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-neuvector-1.6.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-neuvector-1.6.8
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-neuvector-1.6.9
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-neuvector-1.7.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-nfs-provisioner-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-nfs-provisioner-0.2.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-nfs-provisioner-0.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-0.6.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-0.8.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-0.9.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.10.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.11.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.12.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.4.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.5.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.6.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.7.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.8.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-1.9.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-2.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-2.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-2.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openebs-2.5.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-openfaas-5.7.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-phpbb-2.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-phpbb-6.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portshift-operator-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.10
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.7
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.8
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.0.9
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-1.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-essentials-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-essentials-1.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-essentials-1.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-portworx-essentials-1.0.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-prometheus-6.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-prometheus-9.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-redis-10.6.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-redis-3.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-redis-9.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-redskyops-0.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-redskyops-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-splice-helm-0.1.7
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.10
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.11
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.13
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.14
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.15
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.16
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.17
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.2.19
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-storageos-operator-0.3.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-sysdig-1.4.22
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-tidb-operator-v1.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-tidb-operator-v1.1.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-tidb-operator-v1.1.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-tidb-operator-v1.1.7
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-traefik-1.0.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-vault-operator-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-vault-operator-0.1.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-windocks-1.5.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-wordpress-1.0.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-wordpress-2.1.10
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-wordpress-2.1.11
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-wordpress-2.1.12
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-wordpress-7.3.8
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/library-wordpress-9.0.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-cis-benchmark-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-cis-benchmark-0.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-cis-benchmark-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-cis-benchmark-0.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-external-dns-0.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-external-dns-0.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-external-dns-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-external-dns-0.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-external-dns-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-external-dns-0.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-gatekeeper-operator-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-0.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.4.1000
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.4.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.4.300
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.4.400
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.4.600
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.4.700
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.4.900
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.5.800
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.5.900
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.5.901
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-istio-1.5.920
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.3.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.3.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.4.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.5.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-k3s-upgrader-0.6.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.1.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.1.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.2.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.2.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.2.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.2.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-logging-0.4.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.0.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.0.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.0.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.0.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.0.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.0.6
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.0.7
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.1.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.1.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.1.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.1.3
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.1.4
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.1.5
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.2.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.2.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.2.2
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.3.0
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.3.1
kubectl delete -n cattle-global-data   catalogtemplateversion.management.cattle.io/system-library-rancher-monitoring-0.3.2
kubectl delete -n local   clusterregistrationtoken.management.cattle.io/default-token
kubectl delete -n local   clusterroletemplatebinding.management.cattle.io/local-fleet-local-owner
kubectl delete -n local   clusterroletemplatebinding.management.cattle.io/u-b4qkhsnliz-admin
kubectl delete -n local   node.management.cattle.io/machine-9tlk4
kubectl delete -n local   node.management.cattle.io/machine-jlrzt
kubectl delete -n local   node.management.cattle.io/machine-lx7w2
kubectl delete -n user-q9pv9   preference.management.cattle.io/cluster
kubectl delete -n user-q9pv9   preference.management.cattle.io/locale
kubectl delete -n user-q9pv9   preference.management.cattle.io/seen-whatsnew
kubectl delete -n user-q9pv9   preference.management.cattle.io/theme
kubectl delete -n local   project.management.cattle.io/p-7cqfk
kubectl delete -n local   project.management.cattle.io/p-8h7s7
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v5.0.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v5.2.3
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v5.2.3.4
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v5.2.3.5
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v5.2.3.6
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v5.2.7.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v6.0.3.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v6.0.3.2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v6.0.3.3
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/aci-v6.0.4.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.13
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.15
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.15-privileged
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.15.12
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.16
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.17
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.17-privileged
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v1.8
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.16.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.16.5
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.17.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.19.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.21.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.22.5
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.22.5-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.24.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.25.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.26.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.26.1-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/calico-v3.27.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.13
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.15
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.15-privileged
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.15-privileged-calico3134
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.15.12
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.16
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.17
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.17-privileged
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.17-privileged-calico3134
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v1.8
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.16.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.16.5
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.17.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.19.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.21.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.22.5
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.22.5-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.24.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.25.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.26.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.26.1-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/canal-v3.27.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/coredns-v1.16
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/coredns-v1.17
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/coredns-v1.8
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/coredns-v1.8.3
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/coredns-v1.8.3-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/coredns-v1.8.3-rancher3
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v0.14.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v0.14.0-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v0.19.2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v0.21.4
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v0.24.2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v1.15
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v1.16
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/flannel-v1.8
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/kubedns-v1.16
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/kubedns-v1.8
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/metricsserver-v0.5.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/metricsserver-v0.5.2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/metricsserver-v0.6.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/metricsserver-v0.7.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/metricsserver-v1.20
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/metricsserver-v1.8
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v0.48.1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v0.49.3
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.1.0
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.1.0-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.1.0-rancher3
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.1.0-rancher4
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.15
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.15.12
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.2.0-rancher1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.2.0-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.5.1-rancher2
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.7.0-rancher1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.8
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.8.1-rancher1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.9.4-rancher1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nginxingress-v1.9.6-rancher1
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nodelocal-v1.15
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/nodelocal-v1.21
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/weave-v1.16
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/weave-v1.20
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/weave-v1.22
kubectl delete -n cattle-global-data   rkeaddon.management.cattle.io/weave-v1.8
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.10
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.11
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.12
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.13
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.14
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.14.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.14.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.11-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.12-rancher2-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.12-rancher2-3
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.12-rancher2-5
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.12-rancher2-8
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.6-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.15.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.10-rancher2-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.13-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.15-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.15-rancher1-4
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.6-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.16.8-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.17
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.18
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.19
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.20
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.21
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.22
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.22.7-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.23
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.23.4-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.24
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.25
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.26
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.27
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.28
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/v1.9
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.15
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.16
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.17
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.18
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.19
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.20
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.21
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.22
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.22.7-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.23
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.23.4-rancher1-2
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.24
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.25
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.26
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.27
kubectl delete -n cattle-global-data   rkek8sserviceoption.management.cattle.io/wv1.28
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.10.0-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.10.1-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.10.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.10.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.10.3-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.10.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.10.5-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.1-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.2-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.2-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.9-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.11.9-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.0-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.1-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.10-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.5-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.6-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.7-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.7-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.7-rancher1-4
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.12.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.1-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.1-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.10-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.12-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.4-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.5-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.5-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.13.9-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.1-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.1-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.10-rancher1-0
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.8-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.14.9-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.0-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.11-rancher1-0
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.11-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.11-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher2-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher2-4
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher2-5
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher2-6
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher2-7
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.12-rancher2-8
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.2-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.4-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.5-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.5-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.6-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.15.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.1-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.10-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.10-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.13-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.15-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.15-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.15-rancher1-4
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.2-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.2-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.6-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.8-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.16.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.0-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.0-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.13-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.16-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.16-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.16-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.17-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.17-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.17-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.17-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.17-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.17-rancher2-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.17-rancher2-4
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.2-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.2-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.4-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.6-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.6-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.17.9-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.10-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.14-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.14-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.15-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.15-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.16-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.16-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.16-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.17-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.17-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.17-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.18-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.18-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.20-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.20-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.20-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.3-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.3-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.6-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.18.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.14-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.15-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.16-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.16-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.16-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.16-rancher1-4
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.16-rancher1-5
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.16-rancher1-6
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.16-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.2-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.3-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.3-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.19.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.10-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.11-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.12-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.14-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.15-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.15-rancher1-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.15-rancher1-4
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.15-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.15-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.20.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.6-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.8-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.21.9-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.16-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.17-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.17-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.5-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.7-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.22.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.16-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.16-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.16-rancher2-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.4-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.23.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.10-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.10-rancher4-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.13-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.13-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.16-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.17-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.2-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.4-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.24.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.16-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.16-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.16-rancher2-3
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.6-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.6-rancher4-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.9-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.25.9-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.11-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.11-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.13-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.15-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.4-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.26.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.10-rancher1-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.11-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.12-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.13-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.14-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.6-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.8-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.27.8-rancher2-2
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.28.10-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.28.7-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.28.8-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.28.9-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.8.11-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.9.5-rancher1-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.9.7-rancher2-1
kubectl delete -n cattle-global-data   rkek8ssystemimage.management.cattle.io/v1.9.7-rancher2-2
kubectl delete -n fleet-local   cluster.provisioning.cattle.io/local
kubectl delete -n fleet-default   amazonec2config.rke-machine-config.cattle.io/nc-nh-rancher-test-cluster-yjlee-pool-yjlee1-wqgrf
