kubectl delete clusterrepo.catalog.cattle.io/rancher-charts
kubectl delete clusterrepo.catalog.cattle.io/rancher-partner-charts
kubectl delete clusterrepo.catalog.cattle.io/rancher-rke2-charts
kubectl delete content.fleet.cattle.io/s-7c22cf983c7490081db58d5a2785489c4a6448a1fe833c67f09c86e95f408
kubectl delete apiservice.management.cattle.io/git-webhook
kubectl delete authconfig.management.cattle.io/activedirectory
kubectl delete authconfig.management.cattle.io/adfs
kubectl delete authconfig.management.cattle.io/azuread
kubectl delete authconfig.management.cattle.io/freeipa
kubectl delete authconfig.management.cattle.io/github
kubectl delete authconfig.management.cattle.io/googleoauth
kubectl delete authconfig.management.cattle.io/keycloak
kubectl delete authconfig.management.cattle.io/keycloakoidc
kubectl delete authconfig.management.cattle.io/local
kubectl delete authconfig.management.cattle.io/oidc
kubectl delete authconfig.management.cattle.io/okta
kubectl delete authconfig.management.cattle.io/openldap
kubectl delete authconfig.management.cattle.io/ping
kubectl delete authconfig.management.cattle.io/shibboleth
kubectl delete catalog.management.cattle.io/helm3-library
kubectl delete catalog.management.cattle.io/library
kubectl delete catalog.management.cattle.io/system-library
kubectl delete cluster.management.cattle.io/local
kubectl delete dynamicschema.management.cattle.io/amazonec2config
kubectl delete dynamicschema.management.cattle.io/amazonec2credentialconfig
kubectl delete dynamicschema.management.cattle.io/amazonelasticcontainerserviceconfig
kubectl delete dynamicschema.management.cattle.io/azureconfig
kubectl delete dynamicschema.management.cattle.io/azurecredentialconfig
kubectl delete dynamicschema.management.cattle.io/azurekubernetesserviceconfig
kubectl delete dynamicschema.management.cattle.io/cluster
kubectl delete dynamicschema.management.cattle.io/credentialconfig
kubectl delete dynamicschema.management.cattle.io/digitaloceanconfig
kubectl delete dynamicschema.management.cattle.io/digitaloceancredentialconfig
kubectl delete dynamicschema.management.cattle.io/googleconfig
kubectl delete dynamicschema.management.cattle.io/googlecredentialconfig
kubectl delete dynamicschema.management.cattle.io/googlekubernetesengineconfig
kubectl delete dynamicschema.management.cattle.io/harvesterconfig
kubectl delete dynamicschema.management.cattle.io/harvestercredentialconfig
kubectl delete dynamicschema.management.cattle.io/linodeconfig
kubectl delete dynamicschema.management.cattle.io/linodecredentialconfig
kubectl delete dynamicschema.management.cattle.io/nodeconfig
kubectl delete dynamicschema.management.cattle.io/nodetemplateconfig
kubectl delete dynamicschema.management.cattle.io/openstackconfig
kubectl delete dynamicschema.management.cattle.io/openstackcredentialconfig
kubectl delete dynamicschema.management.cattle.io/vmwarevsphereconfig
kubectl delete dynamicschema.management.cattle.io/vmwarevspherecredentialconfig
kubectl delete feature.management.cattle.io/continuous-delivery
kubectl delete feature.management.cattle.io/external-rules
kubectl delete feature.management.cattle.io/fleet
kubectl delete feature.management.cattle.io/harvester
kubectl delete feature.management.cattle.io/harvester-baremetal-container-workload
kubectl delete feature.management.cattle.io/istio-virtual-service-ui
kubectl delete feature.management.cattle.io/legacy
kubectl delete feature.management.cattle.io/multi-cluster-management
kubectl delete feature.management.cattle.io/provisioningv2-fleet-workspace-back-population
kubectl delete feature.management.cattle.io/rke1-custom-node-cleanup
kubectl delete feature.management.cattle.io/rke2
kubectl delete feature.management.cattle.io/token-hashing
kubectl delete feature.management.cattle.io/unsupported-storage-drivers
kubectl delete fleetworkspace.management.cattle.io/fleet-default
kubectl delete fleetworkspace.management.cattle.io/fleet-local
kubectl delete globalrolebinding.management.cattle.io/globalrolebinding-drl5n
kubectl delete globalrolebinding.management.cattle.io/grb-jxdql
kubectl delete globalrole.management.cattle.io/admin
kubectl delete globalrole.management.cattle.io/authn-manage
kubectl delete globalrole.management.cattle.io/catalogs-manage
kubectl delete globalrole.management.cattle.io/catalogs-use
kubectl delete globalrole.management.cattle.io/clusters-create
kubectl delete globalrole.management.cattle.io/clustertemplaterevisions-create
kubectl delete globalrole.management.cattle.io/clustertemplates-create
kubectl delete globalrole.management.cattle.io/features-manage
kubectl delete globalrole.management.cattle.io/kontainerdrivers-manage
kubectl delete globalrole.management.cattle.io/nodedrivers-manage
kubectl delete globalrole.management.cattle.io/podsecuritypolicytemplates-manage
kubectl delete globalrole.management.cattle.io/restricted-admin
kubectl delete globalrole.management.cattle.io/roles-manage
kubectl delete globalrole.management.cattle.io/settings-manage
kubectl delete globalrole.management.cattle.io/user
kubectl delete globalrole.management.cattle.io/user-base
kubectl delete globalrole.management.cattle.io/users-manage
kubectl delete globalrole.management.cattle.io/view-rancher-metrics
kubectl delete kontainerdriver.management.cattle.io/aliyunkubernetescontainerservice
kubectl delete kontainerdriver.management.cattle.io/amazonelasticcontainerservice
kubectl delete kontainerdriver.management.cattle.io/azurekubernetesservice
kubectl delete kontainerdriver.management.cattle.io/baiducloudcontainerengine
kubectl delete kontainerdriver.management.cattle.io/googlekubernetesengine
kubectl delete kontainerdriver.management.cattle.io/huaweicontainercloudengine
kubectl delete kontainerdriver.management.cattle.io/linodekubernetesengine
kubectl delete kontainerdriver.management.cattle.io/opentelekomcloudcontainerengine
kubectl delete kontainerdriver.management.cattle.io/oraclecontainerengine
kubectl delete kontainerdriver.management.cattle.io/rancherkubernetesengine
kubectl delete kontainerdriver.management.cattle.io/tencentkubernetesengine
kubectl delete nodedriver.management.cattle.io/aliyunecs
kubectl delete nodedriver.management.cattle.io/amazonec2
kubectl delete nodedriver.management.cattle.io/azure
kubectl delete nodedriver.management.cattle.io/cloudca
kubectl delete nodedriver.management.cattle.io/cloudscale
kubectl delete nodedriver.management.cattle.io/digitalocean
kubectl delete nodedriver.management.cattle.io/exoscale
kubectl delete nodedriver.management.cattle.io/google
kubectl delete nodedriver.management.cattle.io/harvester
kubectl delete nodedriver.management.cattle.io/linode
kubectl delete nodedriver.management.cattle.io/nutanix
kubectl delete nodedriver.management.cattle.io/oci
kubectl delete nodedriver.management.cattle.io/openstack
kubectl delete nodedriver.management.cattle.io/otc
kubectl delete nodedriver.management.cattle.io/outscale
kubectl delete nodedriver.management.cattle.io/packet
kubectl delete nodedriver.management.cattle.io/pinganyunecs
kubectl delete nodedriver.management.cattle.io/pnap
kubectl delete nodedriver.management.cattle.io/rackspace
kubectl delete nodedriver.management.cattle.io/softlayer
kubectl delete nodedriver.management.cattle.io/vmwarevsphere
kubectl delete podsecurityadmissionconfigurationtemplate.management.cattle.io/rancher-privileged
kubectl delete podsecurityadmissionconfigurationtemplate.management.cattle.io/rancher-restricted
kubectl delete podsecuritypolicytemplate.management.cattle.io/restricted
kubectl delete podsecuritypolicytemplate.management.cattle.io/restricted-noroot
kubectl delete podsecuritypolicytemplate.management.cattle.io/unrestricted
kubectl delete roletemplate.management.cattle.io/admin
kubectl delete roletemplate.management.cattle.io/backups-manage
kubectl delete roletemplate.management.cattle.io/cluster-admin
kubectl delete roletemplate.management.cattle.io/cluster-member
kubectl delete roletemplate.management.cattle.io/cluster-owner
kubectl delete roletemplate.management.cattle.io/clustercatalogs-manage
kubectl delete roletemplate.management.cattle.io/clustercatalogs-view
kubectl delete roletemplate.management.cattle.io/clusterroletemplatebindings-manage
kubectl delete roletemplate.management.cattle.io/clusterroletemplatebindings-view
kubectl delete roletemplate.management.cattle.io/configmaps-manage
kubectl delete roletemplate.management.cattle.io/configmaps-view
kubectl delete roletemplate.management.cattle.io/create-ns
kubectl delete roletemplate.management.cattle.io/edit
kubectl delete roletemplate.management.cattle.io/ingress-manage
kubectl delete roletemplate.management.cattle.io/ingress-view
kubectl delete roletemplate.management.cattle.io/monitoring-ui-view
kubectl delete roletemplate.management.cattle.io/navlinks-manage
kubectl delete roletemplate.management.cattle.io/navlinks-view
kubectl delete roletemplate.management.cattle.io/nodes-manage
kubectl delete roletemplate.management.cattle.io/nodes-view
kubectl delete roletemplate.management.cattle.io/persistentvolumeclaims-manage
kubectl delete roletemplate.management.cattle.io/persistentvolumeclaims-view
kubectl delete roletemplate.management.cattle.io/project-member
kubectl delete roletemplate.management.cattle.io/project-monitoring-readonly
kubectl delete roletemplate.management.cattle.io/project-owner
kubectl delete roletemplate.management.cattle.io/projectcatalogs-manage
kubectl delete roletemplate.management.cattle.io/projectcatalogs-view
kubectl delete roletemplate.management.cattle.io/projectroletemplatebindings-manage
kubectl delete roletemplate.management.cattle.io/projectroletemplatebindings-view
kubectl delete roletemplate.management.cattle.io/projects-create
kubectl delete roletemplate.management.cattle.io/projects-view
kubectl delete roletemplate.management.cattle.io/read-only
kubectl delete roletemplate.management.cattle.io/secrets-manage
kubectl delete roletemplate.management.cattle.io/secrets-view
kubectl delete roletemplate.management.cattle.io/serviceaccounts-manage
kubectl delete roletemplate.management.cattle.io/serviceaccounts-view
kubectl delete roletemplate.management.cattle.io/services-manage
kubectl delete roletemplate.management.cattle.io/services-view
kubectl delete roletemplate.management.cattle.io/storage-manage
kubectl delete roletemplate.management.cattle.io/view
kubectl delete roletemplate.management.cattle.io/workloads-manage
kubectl delete roletemplate.management.cattle.io/workloads-view
kubectl delete setting.management.cattle.io/agent-image
kubectl delete setting.management.cattle.io/agent-rollout-timeout
kubectl delete setting.management.cattle.io/agent-rollout-wait
kubectl delete setting.management.cattle.io/aks-refresh
kubectl delete setting.management.cattle.io/api-ui-version
kubectl delete setting.management.cattle.io/auth-image
kubectl delete setting.management.cattle.io/auth-token-max-ttl-minutes
kubectl delete setting.management.cattle.io/auth-user-info-max-age-seconds
kubectl delete setting.management.cattle.io/auth-user-info-resync-cron
kubectl delete setting.management.cattle.io/auth-user-session-ttl-minutes
kubectl delete setting.management.cattle.io/authorization-cache-ttl-seconds
kubectl delete setting.management.cattle.io/authorization-deny-cache-ttl-seconds
kubectl delete setting.management.cattle.io/azure-group-cache-size
kubectl delete setting.management.cattle.io/cacerts
kubectl delete setting.management.cattle.io/chart-default-branch
kubectl delete setting.management.cattle.io/cli-url-darwin
kubectl delete setting.management.cattle.io/cli-url-linux
kubectl delete setting.management.cattle.io/cli-url-windows
kubectl delete setting.management.cattle.io/cluster-agent-default-affinity
kubectl delete setting.management.cattle.io/cluster-controller-start-count
kubectl delete setting.management.cattle.io/cluster-template-enforcement
kubectl delete setting.management.cattle.io/config-map-name
kubectl delete setting.management.cattle.io/csi-proxy-agent-url
kubectl delete setting.management.cattle.io/csi-proxy-agent-version
kubectl delete setting.management.cattle.io/csp-adapter-min-version
kubectl delete setting.management.cattle.io/delete-inactive-user-after
kubectl delete setting.management.cattle.io/disable-inactive-user-after
kubectl delete setting.management.cattle.io/eks-refresh
kubectl delete setting.management.cattle.io/eks-refresh-cron
kubectl delete setting.management.cattle.io/engine-install-url
kubectl delete setting.management.cattle.io/engine-iso-url
kubectl delete setting.management.cattle.io/engine-newest-version
kubectl delete setting.management.cattle.io/engine-supported-range
kubectl delete setting.management.cattle.io/eula-agreed
kubectl delete setting.management.cattle.io/first-login
kubectl delete setting.management.cattle.io/fleet-agent-default-affinity
kubectl delete setting.management.cattle.io/fleet-default-workspace-name
kubectl delete setting.management.cattle.io/fleet-min-version
kubectl delete setting.management.cattle.io/fleet-version
kubectl delete setting.management.cattle.io/github-proxy-api-url
kubectl delete setting.management.cattle.io/gke-refresh
kubectl delete setting.management.cattle.io/global-registry-enabled
kubectl delete setting.management.cattle.io/helm-max-history
kubectl delete setting.management.cattle.io/helm-version
kubectl delete setting.management.cattle.io/hide-local-cluster
kubectl delete setting.management.cattle.io/ignore-node-name
kubectl delete setting.management.cattle.io/ingress-ip-domain
kubectl delete setting.management.cattle.io/initial-docker-root-dir
kubectl delete setting.management.cattle.io/install-uuid
kubectl delete setting.management.cattle.io/internal-cacerts
kubectl delete setting.management.cattle.io/internal-server-url
kubectl delete setting.management.cattle.io/is-rke
kubectl delete setting.management.cattle.io/jailer-timeout
kubectl delete setting.management.cattle.io/k3s-default-version
kubectl delete setting.management.cattle.io/k8s-version
kubectl delete setting.management.cattle.io/k8s-version-to-images
kubectl delete setting.management.cattle.io/k8s-version-to-service-options
kubectl delete setting.management.cattle.io/k8s-versions-current
kubectl delete setting.management.cattle.io/k8s-versions-deprecated
kubectl delete setting.management.cattle.io/kdm-branch
kubectl delete setting.management.cattle.io/kubeconfig-default-token-ttl-minutes
kubectl delete setting.management.cattle.io/kubeconfig-generate-token
kubectl delete setting.management.cattle.io/machine-provision-image
kubectl delete setting.management.cattle.io/machine-provision-image-pull-policy
kubectl delete setting.management.cattle.io/machine-version
kubectl delete setting.management.cattle.io/namespace
kubectl delete setting.management.cattle.io/no-default-admin
kubectl delete setting.management.cattle.io/partner-chart-default-branch
kubectl delete setting.management.cattle.io/password-min-length
kubectl delete setting.management.cattle.io/peer-service
kubectl delete setting.management.cattle.io/rancher-webhook-version
kubectl delete setting.management.cattle.io/restricted-default-admin
kubectl delete setting.management.cattle.io/rke-metadata-config
kubectl delete setting.management.cattle.io/rke-version
kubectl delete setting.management.cattle.io/rke2-chart-default-branch
kubectl delete setting.management.cattle.io/rke2-default-version
kubectl delete setting.management.cattle.io/rotate-certs-if-expiring-in-days
kubectl delete setting.management.cattle.io/server-image
kubectl delete setting.management.cattle.io/server-url
kubectl delete setting.management.cattle.io/server-version
kubectl delete setting.management.cattle.io/shell-image
kubectl delete setting.management.cattle.io/skip-hosted-cluster-chart-installation
kubectl delete setting.management.cattle.io/system-agent-install-script
kubectl delete setting.management.cattle.io/system-agent-installer-image
kubectl delete setting.management.cattle.io/system-agent-upgrade-image
kubectl delete setting.management.cattle.io/system-agent-version
kubectl delete setting.management.cattle.io/system-catalog
kubectl delete setting.management.cattle.io/system-default-registry
kubectl delete setting.management.cattle.io/system-feature-chart-refresh-seconds
kubectl delete setting.management.cattle.io/system-managed-charts-operation-timeout
kubectl delete setting.management.cattle.io/system-namespaces
kubectl delete setting.management.cattle.io/system-upgrade-controller-chart-version
kubectl delete setting.management.cattle.io/telemetry-opt
kubectl delete setting.management.cattle.io/telemetry-uid
kubectl delete setting.management.cattle.io/tls-ciphers
kubectl delete setting.management.cattle.io/tls-min-version
kubectl delete setting.management.cattle.io/ui-banners
kubectl delete setting.management.cattle.io/ui-brand
kubectl delete setting.management.cattle.io/ui-community-links
kubectl delete setting.management.cattle.io/ui-custom-links
kubectl delete setting.management.cattle.io/ui-dashboard-harvester-legacy-plugin
kubectl delete setting.management.cattle.io/ui-dashboard-index
kubectl delete setting.management.cattle.io/ui-dashboard-path
kubectl delete setting.management.cattle.io/ui-default-landing
kubectl delete setting.management.cattle.io/ui-favicon
kubectl delete setting.management.cattle.io/ui-feedback-form
kubectl delete setting.management.cattle.io/ui-index
kubectl delete setting.management.cattle.io/ui-issues
kubectl delete setting.management.cattle.io/ui-k8s-default-version-range
kubectl delete setting.management.cattle.io/ui-k8s-supported-versions-range
kubectl delete setting.management.cattle.io/ui-offline-preferred
kubectl delete setting.management.cattle.io/ui-path
kubectl delete setting.management.cattle.io/ui-performance
kubectl delete setting.management.cattle.io/ui-pl
kubectl delete setting.management.cattle.io/ui-preferred
kubectl delete setting.management.cattle.io/user-last-login-default
kubectl delete setting.management.cattle.io/user-retention-cron
kubectl delete setting.management.cattle.io/user-retention-dry-run
kubectl delete setting.management.cattle.io/whitelist-domain
kubectl delete setting.management.cattle.io/whitelist-envvars
kubectl delete setting.management.cattle.io/wins-agent-install-script
kubectl delete setting.management.cattle.io/wins-agent-upgrade-image
kubectl delete setting.management.cattle.io/wins-agent-version
kubectl delete token.management.cattle.io/kubeconfig-user-q9pv9dwxlw
kubectl delete token.management.cattle.io/telemetry
kubectl delete token.management.cattle.io/token-9rswm
kubectl delete token.management.cattle.io/token-kvlws
kubectl delete token.management.cattle.io/u-mo773yttt4
kubectl delete userattribute.management.cattle.io/user-q9pv9
kubectl delete user.management.cattle.io/u-b4qkhsnliz
kubectl delete user.management.cattle.io/user-q9pv9
