kube-apiserver-extra-mount: 
   - "/var/log/kubernetes/:/var/log/kubernetes/:rw"
   - "/etc/rancher/rke2/:/etc/rancher/rke2/:ro" 

kube-apiserver-arg:
   - --audit-policy-file=/etc/rancher/rke2/k8s-api-audit-policies.yml
   - --audit-log-path=/var/log/kubernetes/audit/audit.log
   - --audit-log-maxage=7
