apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: metricbeat-kube-state-leader
  namespace: kube-system
spec:
  holderIdentity: ""
  leaseDurationSeconds: 15
  acquireTime: null
  renewTime: null
  leaseTransitions: 0
