---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat-kube-state
  namespace: kube-system
  labels:
    k8s-app: metricbeat-kube-state
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: metricbeat-kube-state
  template:
    metadata:
      labels:
        k8s-app: metricbeat-kube-state
    spec:
      serviceAccountName: metricbeat
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                      - metricbeat-kube-state
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: metricbeat-kube-state
        image: docker.elastic.co/beats/metricbeat:8.9.2
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps aux |grep -i metricbeat.yml"
          initialDelaySeconds: 30
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: ES_HOST
          value: "172.31.18.85"
        - name: ES_PORT
          value: "9200"
        - name: INDEX_TEMPLATE
          value: "k8s-kube-state-metric"
        - name: KUBE_STATE_METRIC_URL
          value: "rancher-monitoring-kube-state-metrics.cattle-monitoring-system.svc.cluster.local.:8080"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: metricbeat-deployment-config
