---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: kube-system
data:
  metricbeat.yml: |-
    metricbeat.modules:
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 30s
      host: "${HOST_IP}"
      hosts: ["https://${HOST_IP}:10250"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: "none"

processors:                                                                                                                                                                                                                                       - add_kubernetes_metadata:                                                                                                                                                                                                                          in_cluster: false                                                                                                                                                                                                                               host: "rancher-master-test2"                                                                                                                                                                                                                - add_fields:
      target: ""
      fields:                                                                                                                                                                                                                                           NHcenter: "centerA"                                                                                                                                                                                                                             NHcluster: "clusterA"
    
    output.elasticsearch:
      hosts: ["${ES_HOST}:${ES_PORT}"]
      index: "${INDEX_TEMPLATE}"
    setup.template.name: "${INDEX_TEMPLATE}"
    setup.template.pattern: "${INDEX_TEMPLATE}"
