---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  namespace: kube-system
data:
  metricbeat.yml: |-
    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
          unique: true
          leader_lease: metricbeat-leader-election
          identifier: leader-metricbeat
          templates:
            - config:
                - module: kubernetes
                  add_metadata: true
                  metricsets:
                    - state_node
                    - state_daemonset
                    - state_deployment
                    - state_replicaset
                    - state_statefulset
                    - state_pod
                    - state_container
                    - state_job
                    - state_cronjob
                    - state_resourcequota
                    - state_service
                    - state_persistentvolume
                    - state_persistentvolumeclaim
                    - state_storageclass
                  period: 30s
                  hosts: ["${KUBE_STATE_METRIC_URL}"]
    processors: 
      - add_fields:
          target: ""
          fields:
            NHcenter: "centerA"
            NHcluster: "clusterA" 
    output.elasticsearch:
      hosts: ["${ES_HOST}:${ES_PORT}"]
      index: "${INDEX_TEMPLATE}"
    setup.template.name: "${INDEX_TEMPLATE}"
    setup.template.pattern: "${INDEX_TEMPLATE}"
