filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
            and:
              - contains:
                  kubernetes.labels.NHapp: "app"
          config:
            - type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
processors:
  - add_kubernetes_metadata:
      in_cluster: false
      host: "rancher-master-test2"
  - add_fields:
      target: ""  
      fields:
        NHcenter: "centerA"
        NHcluster: "clusterA"

output.elasticsearch:
  hosts: ["http://172.31.29.94:9200"]
  index: "k8s-pod-log-app"

setup.template.name: "k8s-pod-log-app"
setup.template.pattern: "k8s-pod-log-app"
