filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/audit/audit.log
  fields_under_root: true
  fields:
    NHcenter: "centerA" 
    NHcluster: "clusterA"

processors:
- add_host_metadata: {}

output.elasticsearch:
  hosts: ["172.31.18.85:9200"]
  index: "k8s-node-log-audit"

setup.template.name: "k8s-node-log-audit"
setup.template.pattern: "k8s-node-log-audit"
