filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/kubernetes/audit/audit.log
  fields_under_root: true
  fields:
    NHcenter: "centerA"
    NHcluster: "clusterA"
  parsers:
    - ndjson:
        keys_under_root: true
processors:
- add_host_metadata: {}

output.elasticsearch:
  hosts: ["172.31.18.85:9200"]
  index: "k8s-pod-log-audit"
setup.template.name: "k8s-pod-log-audit"
setup.template.pattern: "k8s-pod-log-audit"
